development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: cassio.kawakita@gmail.com
  :password: 1q2w3e4r5t!P
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: cassio.kawakita@gmail.com
  :password: 1q2w3e4r5t!P
  :enable_starttls_auto: true